[package]
name = "obs-random-line"
version = "0.1.0"
authors = ["Markus Seidl <mark@bearo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
